.TH MAKE_DB 1 "March 30, 2002"
.SH NAME
make_db \- Create the image database needed by pixelize
.SH SYNOPSIS
.B make_db
image_files
.SH DESCRIPTION
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.PP
.B make_db
is a program that scans pictures and creates a file called
.B pic_db.dat
in the current directory. This file is used by
.B pixelize
when "rendering" images.
.SH OPTIONS
None.
.SH BUGS
Please report any bugs you find to Paul Wilkins <pwilkins@lashwhip.com>.
.SH LICENCE
.B make_db
is covered by the GNU General Public License (GPL), version 2 or later.
.SH SEE ALSO
.BR pixelize (1).
.SH AUTHOR
Paul Wilkins <pwilkins@lashwhip.com>
.PP
This manual page was written by Uwe Hermann <uwe@debian.org>,
for the Debian GNU/Linux system. It is licensed under the terms of the
GNU GPL, version 2 or later.
